version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_recommendMe
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}       
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER}              
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}           
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  data:
    build: ./Data
    env_file:
      - .env
    profiles: ["full-setup", "data-only"]
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
    - ./logs:/app/logs
    - ./Data/img_recommendMe:/app/images
    restart: "no"

  backend:
    build: ./Backend
    env_file:
      - .env
    profiles: ["full-setup", "backend-only"]
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./Backend:/app 
      - ./Data/img_recommendMe:/app/media
    command: python API_recommendme/manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data:
