# Generated by Django 4.2.27 on 2026-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genremov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genre_tmdb', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'GenreMov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genretv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genre_tmdb', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'GenreTv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movie_Genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movie_Providers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tmdb', models.IntegerField(unique=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=150, null=True)),
                ('original_lenguaje', models.CharField(blank=True, max_length=50, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=150, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Providersmov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider_tmdb', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'ProvidersMov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Providerstv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider_tmdb', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'ProvidersTv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tmdb', models.IntegerField(unique=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=255, null=True)),
                ('original_lenguaje', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_name', models.CharField(blank=True, max_length=80, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=150, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TvGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TV_Genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TvProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TV_Providers',
                'managed': False,
            },
        ),
    ]
