# Generated by Django 4.2.27 on 2026-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_recomendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vectorized_Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.JSONField()),
                ('original_lenguaje', models.JSONField()),
                ('title', models.JSONField()),
                ('keywords', models.JSONField()),
                ('popularity', models.JSONField()),
                ('release_date', models.JSONField()),
                ('director', models.JSONField()),
                ('actors', models.JSONField()),
                ('vote_average', models.JSONField()),
                ('vote_count', models.JSONField()),
                ('gender', models.JSONField()),
                ('movie_vector', models.JSONField()),
            ],
            options={
                'db_table': 'Vectorized_Movies',
                'managed': False,
            },
        ),
    ]
