# Generated by Django 4.2.29 on 2026-06-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_recomendations', '0002_vectorized_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=5)),
                ('display_priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Provider_Countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_provider_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=355, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Providers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Providersmov',
        ),
    ]
